services:
  app:
    build: .
    container_name: comnestindia
    restart: always
    environment:
      GMAIL_USER : ${GMAIL_USER}
      GMAIL_PASS : ${GMAIL_PASS}
    ports:
      - "1006:3000"
    command: ["npm", "run", "start"]
